### ISSUE TITLE
Add support for inserting emojis everywhere

### ISSUE THREAD

**Issue by vladfrangu** [shiraji/emoji#14]
This might sound weird, but why not allow insertion of emojis _everywhere_?

I would find it useful, and probably others would too

**Comment by shiraji** [comment]
Where do you want to insert emojis? Intellij already support adding emoji to comment and string literal. 

I mean if the plugin should support inserting those emoji somehow I would definitely implement them.

**Comment by vladfrangu** [comment]
IntelliJ supports inserting emojis? How? I haven't figured out how to do it yet, I probably should look real quick.

**Comment by shiraji** [comment]
Check **Emoji in Editor**
https://www.jetbrains.com/idea/whatsnew/#v2017-1-user-interface

**Comment by vladfrangu** [comment]
Right, but thats just rendering.. I mean inserting them in things like strings

**Comment by shiraji** [comment]
I don't understand what you mean...maybe because I'm using Japanese IME. Things like this can easily happens to me

![2017-08-09 0 40 48](https://user-images.githubusercontent.com/3675458/29080697-6ff480e2-7c9b-11e7-914a-5abf35135fbc.png)

**Comment by vladfrangu** [comment]
So, lets say I want to write a string and end it with an emoji, 😃 for example. I'd love to be able to type `:smi`, choose the emoji and it going in the string

**Comment by shiraji** [comment]
At this point, you want to insert or get suggestion for 😄 

![2017-08-09 0 47 20](https://user-images.githubusercontent.com/3675458/29081030-627ad690-7c9c-11e7-99e5-dbfe45e94d6c.png)

**Comment by vladfrangu** [comment]
This is what I'm thinking off, but I don't know if its doable
 ![image](https://i.kingdgrizzle.ml/2017/08/R0y5Q6.png)

**Comment by parthsharma1996** [comment]
Are there any plans for implementation of this? I would love this functionality!

**Comment by shiraji** [comment]
I'm not quite sure what you guys want at this moment. Where do you want to put this functionality? @parthsharma1996

**Comment by parthsharma1996** [comment]
We want to be able to type `:` anywhere in the editor and insert emojis there, not just in the git commit window

**Comment by shiraji** [comment]
Are you talking about inside the code as well? Because some language (e.g. ruby, kotlin, Swift) use `:` as a syntax, I don't think that is good idea for developers.

**Comment by parthsharma1996** [comment]
@shiraji Well maybe you could only allow emoji suggestion to appear in auto completion within strings? 

Even without that maybe you could give the option to allow it everywhere which users can check or uncheck based on their preference (e.g. I would keep it on, because I write emojis in the strings a lot)

Can you see the behaviour of https://marketplace.visualstudio.com/items?itemName=bierner.emojisense ? It allows you to use emojis in the editor

**Comment by shiraji** [comment]
Can you type `cmd+ctrl+space` to insert emoji in MacOS? (I'm not sure for Ubuntu. see https://youtrack.jetbrains.com/issue/IDEA-192107 )

---

I mean I understand what you guys want. You guys want to insert emoji (unicode) if the text starts from `:` in everywhere

Here is the list.
https://unicode.org/emoji/charts/full-emoji-list.html

If you guys really really want, I can create other plugins that use this list to insert emoji everywhere.

**Comment by parthsharma1996** [comment]
> If you guys really really want, I can create other plugins that use this list to insert emoji everywhere.

@shiraji  Please do!

**Comment by shiraji** [comment]
Now, I'm starting creating new plugin. Here is the gif

![emoji](https://user-images.githubusercontent.com/3675458/58378115-f315f500-7fc8-11e9-9af2-2fa9eb71c567.gif)

**Comment by shiraji** [comment]
Hey guys

Today JetBrains approved my new plugin called "Yet another emoji support" plugin.

https://plugins.jetbrains.com/plugin/12512-yet-another-emoji-support
https://github.com/shiraji/yet-another-emoji-support

This is whole new plugin that inserts emoji in editor. In case you are interested to use that, please uninstall this emoji support plugin and then install new one. Otherwise, I'm not sure what happen to your IDE. 

So, I'm going to close this issue since this "emoji support" plugin won't implement this feature. Please use "Yet another emoji support" plugin.

Thanks!

P.S. I'm **not** going to stop maintain this "emoji support" plugin.
